[[redirects]]
  from = "/api/*"
  to = "https://serenusai.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/*"
  to = "https://serenusai.onrender.com/webhook/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/stripe/*"
  to = "https://serenusai.onrender.com/stripe/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
